export const REDIRECT_URLS = {
  DASHBOARD: {
    OVERVIEW: "/dashboard",
    PITCH: "/dashboard/pitch",
    CREATE_PITCH: "/dashboard/pitch/create",
    BOOKING: "/dashboard/booking",
    VOUCHER: "/dashboard/voucher",
    CREATE_VOUCHER: "/dashboard/voucher/create",
    STAFF: "/dashboard/staff",
    CREATE_STAFF: "/dashboard/staff/create",
    PROFILE: "/dashboard/profile",
    MESSAGE: "/dashboard/message",
    NOTIFICATION: "/dashboard/notification",
    SERVICE: "/dashboard/service",
    ADVERTISEMENT: "/dashboard/advertisement",
  },
  ADMIN: {
    OVERVIEW: "/admin",
    REGISTRATION: "/admin/registration",
    PITCH: "/admin/pitch",
    VOUCHER: "/admin/voucher",
    CREATE_VOUCHER: "/admin/voucher/create",
    USER: "/admin/user",
    PROFILE: "/admin/profile",
    MESSAGE: "/admin/message",
    NOTIFICATION: "/admin/notification",
    SERVICE: "/admin/service",
    ADVERTISEMENT: "/admin/advertisement",
    REPORT: "/admin/report",
  },
  PERSONAL: {
    PROFILE: "/personal/profile",
    HISTORY: "/personal/history",
    FAVORITE: "/personal/favorite",
  },
  FIND_PITCH: "/#find-pitch",
  PITCH: "/pitch",
  LOGIN: "/login",
  REGISTER: "/register",
  COMMUNITY: "/community",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  VERIFY_PHONE: "/verify-phone",
  CONTACT: "/contact",
  ABOUT_US: "/about-us",
  TERMS_OF_USE: "/terms-of-use",
  PRIVACY: "/privacy",
  PRIVACY_POLICY: "/privacy-policy",
  FAQ: "/faq",
};
